name: "Gosum"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/gosum.yaml"
      - "go.mod"
      - "go.sum"

jobs:
  gosum:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Tidy
        run: |
          rm -f go.sum
          go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ":hammer: Tidy up the Go modules"
          title: "Tidy up the Go module"
          body: |
            Current `go.mod` and `go.sum` don't match the source code.
          branch: go-mod-tidy
          branch-suffix: short-commit-hash
          labels: "Type: Maintenance"