name: Pull Request
on:
  push:
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - .gitignore
      - .all-contributorsrc
      - .github/CONTRIBUTING.md
      - .github/CODE_OF_CONDUCT.md
      - .github/CONTRIBUTION_LICENSE_AGREEMENT.md
    tags:
      - v*
    branches:
      - master
      - development
  pull_request:
    branches-ignore:
      - dependabot/**

jobs:
  checks:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v3

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.29
          args: --tests=0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      # - name: Run tests
      #   run: make test

      - name: Compile the project
        run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2